{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <hogwarts.unit.test_pytest.TestClass object at 0x00000000038D2A20>\n\n    def test_two(self):\n        x=\"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\nunit\\test_pytest.py:34: AssertionError"}, "attachments": [{"name": "stdout", "source": "b7c6b51d-8551-4a96-bd86-a0e11888e2a5-attachment.txt", "type": "text/plain"}], "start": 1577236597565, "stop": 1577236597566, "uuid": "069828b1-1e00-44e1-af98-93baf3368723", "historyId": "6680fc9ec4668e002e11244becd754fc", "testCaseId": "3a9827ca4990735a72abc8997621e3fc", "fullName": "test_pytest.TestClass#test_two", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "MS-20170607LVPH"}, {"name": "thread", "value": "5016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}